package org.csc133.a2w;


import static com.codename1.ui.CN.*;

import com.codename1.charts.util.ColorUtil;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class AppMain {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " +
                    err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form clockForm = new Form("Digital Clock");
        clockStyle.setAlignment(Component.CENTER);//possibly delete
        //Style titleBarColor = clockForm.getToolbar().getTitleComponent().getAllStyles();//META makes this colored
       //titleBarColor.setBgColor(ColorUtil.YELLOW);
        Style clockStyle = new Style();//calling style
        clockStyle.setBgColor(ColorUtil.YELLOW);
        clockForm.getToolbar().setUnselectedStyle(clockStyle);//setting the toolbars style here

        clockForm.getAllStyles().setBgTransparency(200);
        clockForm.getAllStyles().setBgColor(ColorUtil.BLACK);
        clockForm.setLayout(new BorderLayout());//expieremtn with this

        clockForm.add(BorderLayout.CENTER,newDefaultClock(25,1,ColorUtil.BLUE));//META Moved Clock to center

        clockForm.show();
    }
    DigitalClockComponent newDefaultClock(int m ,int p, int ledColor){
        DigitalClockComponent aClock = new DigitalClockComponent();
        aClock.getAllStyles().setPadding(p,p,p,p);
        aClock.getAllStyles().setMargin(m,m,m,m);
        aClock.setLedColor(ledColor);
        return aClock;
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
